export const BASIC_RELEASE = `
I, the undersigned, irreversibly grant to Intellectual Reserve, Inc., its related entities, and their respective employees, agents, and representatives (collectively called “IRI”), the full right to create and obtain, in the past, present, and in the future, images, photographs, video, audio, interviews, stories, personal histories, performances (vocal, instrumental, dramatic, or otherwise), mixes, and any other recordings, documents, or materials, in any now known or future media, of my name, image, voice, likeness, performance, and other items (collectively called “Recordings”). I also authorize IRI to copyright, adapt, edit, translate, summarize, reproduce, perform, display, distribute, publish, license, sublicense, sell, broadcast, post or stream over the Internet, and otherwise use and allow others to use any and all parts of the Recordings, forever and throughout the world, in any and all manners, and in any and all forms of media that IRI believes suitable.

I agree that I shall have no right, title, or interest in or to the Recordings (or to any work comprising or based on the Recordings, in whole or in part), and that all right, title, and interest in and to the Recordings belongs to IRI. I waive any and all right to payment or other compensation arising from or related to the Recordings. I will not state or imply, or allow others to state or imply, that IRI approves of or endorses me or my activities. I further agree to release, defend, and hold IRI harmless from any claims, damages, or liabilities related to the Recordings or IRI’s use thereof. I understand this Release is governed by the laws of the State of Utah, U.S.A.
`;

export const PARENT_RELEASE = `
I, the undersigned, hereby warrant and represent that I am the parent or legal guardian of the minor child named above and printed next to my name below (the “Youth”), that I have full authority to execute this Release on behalf of the Youth, that I have read this Release, and that by signing below I have granted this Release on behalf of the Youth. I hereby agree that I, the Youth, and all other parents or legal guardians, if any, will be bound by all releases, consents, and covenants contained in this Release. I further agree to indemnify and defend IRI against any and all liabilities relating to the Youth’s actions in connection with the Recordings or IRI’s use thereof.
`;
